import RequestProject.Zeta7.Hankel2.MahlerSeries
import RequestProject.Zeta7.Hankel2.VolkenbornExist

/-!
# Mahler profiles via finite differences (paper §4.2, the analytic step of Theorem 4.1)

The Volkenborn integral only sees the values of a function at the natural numbers, and the
Mahler coefficients of `f` are the finite differences `Δ^c f(0)`.  We therefore control
functions through their *profile*: `Prof w f` says that `‖Δ^j f(x)‖₂ ≤ w j` for all natural
`x` and `j` (`Δ = fwdDiff 1`).

* `Prof.mul` — a Leibniz-type product estimate: if `w k · w' (i−k) ≤ B i` for all `k ≤ i`, then
  `Prof w u → Prof w' v → Prof B (u v)`.
* `Adm` — the algebra generated by the constants of norm `≤ 1` and the functions
  `(u + 2t)^{-1}` with `u` odd.  Every admissible function has the geometric profile
  `‖Δ^j f(x)‖ ≤ 2^{-j}` (`Adm.prof`), which is the finite-difference form of the paper's
  bound `v₂(γ_m) ≥ m` for the Mahler coefficients of `G`, and admissible functions are closed
  under differentiation on the ball `‖t‖ < 2` (`Adm.hasDerivAt`).
-/

open Filter Finset Topology Polynomial

namespace Hankel2

local notation "Δ₂" => fwdDiff (1 : ℚ_[2])

/-- The profile bound: `‖Δ^j f(x)‖ ≤ w j` for all natural `x`, `j`. -/
def Prof (w : ℕ → ℝ) (f : ℚ_[2] → ℚ_[2]) : Prop :=
  ∀ x j : ℕ, ‖(Δ₂)^[j] f (x : ℚ_[2])‖ ≤ w j

theorem fwdDiff_mul_eq (u v : ℚ_[2] → ℚ_[2]) :
    Δ₂ (u * v) = Δ₂ u * (fun y => v (y + 1)) + u * Δ₂ v := by
  funext y; simp only [fwdDiff, Pi.mul_apply, Pi.add_apply]; ring

theorem Prof.succ {w : ℕ → ℝ} {u : ℚ_[2] → ℚ_[2]} (hu : Prof w u) :
    Prof (fun j => w (j + 1)) (Δ₂ u) := by
  intro x j
  rw [← Function.iterate_succ_apply]
  exact hu x (j + 1)

theorem Prof.shift {w : ℕ → ℝ} {v : ℚ_[2] → ℚ_[2]} (hv : Prof w v) :
    Prof w (fun y => v (y + 1)) := by
  intro x j
  rw [fwdDiff_iter_comp_add]
  have := hv (x + 1) j
  push_cast at this
  exact this

/-- **Leibniz-type product estimate.** -/
theorem Prof.mul {w w' B : ℕ → ℝ} {u v : ℚ_[2] → ℚ_[2]} (hu : Prof w u) (hv : Prof w' v)
    (hB : ∀ i k, k ≤ i → w k * w' (i - k) ≤ B i) : Prof B (u * v) := by
  intro x j
  induction j generalizing w w' B u v x with
  | zero =>
    simp only [Function.iterate_zero, id_eq, Pi.mul_apply, norm_mul]
    refine le_trans ?_ (hB 0 0 le_rfl)
    have h1 := hu x 0
    have h2 := hv x 0
    simp only [Function.iterate_zero, id_eq] at h1 h2
    exact mul_le_mul h1 h2 (norm_nonneg _) (le_trans (norm_nonneg _) h1)
  | succ j ih =>
    rw [Function.iterate_succ_apply, fwdDiff_mul_eq, fwdDiff_iter_add, Pi.add_apply]
    refine le_trans (IsUltrametricDist.norm_add_le_max _ _) (max_le ?_ ?_)
    · exact ih (w := fun j => w (j + 1)) (B := fun j => B (j + 1)) hu.succ hv.shift
        (fun i k hk => by
          have := hB (i + 1) (k + 1) (by omega)
          rwa [show i + 1 - (k + 1) = i - k by omega] at this) x
    · exact ih (w' := fun j => w' (j + 1)) (B := fun j => B (j + 1)) hu hv.succ
        (fun i k hk => by
          have := hB (i + 1) k (by omega)
          rwa [show i + 1 - k = i - k + 1 by omega] at this) x

theorem Prof.add {w : ℕ → ℝ} {u v : ℚ_[2] → ℚ_[2]} (hu : Prof w u) (hv : Prof w v) :
    Prof w (u + v) := by
  intro x j
  rw [fwdDiff_iter_add, Pi.add_apply]
  exact le_trans (IsUltrametricDist.norm_add_le_max _ _) (max_le (hu x j) (hv x j))

theorem Prof.mono {w w' : ℕ → ℝ} {u : ℚ_[2] → ℚ_[2]} (hu : Prof w u) (h : ∀ j, w j ≤ w' j) :
    Prof w' u := fun x j => le_trans (hu x j) (h j)

theorem Prof.finset_sum {ι : Type*} (s : Finset ι) {w : ℕ → ℝ} (hw : ∀ j, 0 ≤ w j)
    {f : ι → ℚ_[2] → ℚ_[2]} (hf : ∀ i ∈ s, Prof w (f i)) : Prof w (∑ i ∈ s, f i) := by
  classical
  induction s using Finset.induction_on with
  | empty =>
    intro x j
    simp only [Finset.sum_empty]
    rw [show (0 : ℚ_[2] → ℚ_[2]) = fun _ => (0 : ℚ_[2]) from rfl]
    rcases j with _ | j
    · simpa using hw 0
    · rw [Function.iterate_succ_apply, fwdDiff_const, Function.iterate_fixed (by
        rw [fwdDiff_const])]
      simpa using hw (j + 1)
  | insert a s ha ih =>
    rw [Finset.sum_insert ha]
    exact (hf a (mem_insert_self _ _)).add (ih fun i hi => hf i (mem_insert_of_mem hi))

/-! ### The geometric profile -/

/-- The geometric weight `2^{-j}`. -/
noncomputable def geo (j : ℕ) : ℝ := (2 : ℝ)⁻¹ ^ j

theorem geo_nonneg (j : ℕ) : 0 ≤ geo j := by unfold geo; positivity

theorem geo_mul (i k : ℕ) (hk : k ≤ i) : geo k * geo (i - k) = geo i := by
  unfold geo; rw [← pow_add]; congr 1; omega

theorem Prof.geo_mul {u v : ℚ_[2] → ℚ_[2]} (hu : Prof geo u) (hv : Prof geo v) :
    Prof geo (u * v) :=
  hu.mul hv fun i k hk => le_of_eq (Hankel2.geo_mul i k hk)

theorem prof_const {a : ℚ_[2]} (ha : ‖a‖ ≤ 1) : Prof geo (fun _ => a) := by
  intro x j
  rcases j with _ | j
  · simpa [geo] using ha
  · rw [Function.iterate_succ_apply, fwdDiff_const, Function.iterate_fixed (by
      rw [fwdDiff_const])]
    simpa using geo_nonneg (j + 1)

/-- `‖1 + 2y‖ = 1` for `‖y‖ ≤ 1`. -/
theorem norm_one_add_two_mul {y : ℚ_[2]} (hy : ‖y‖ ≤ 1) : ‖1 + 2 * y‖ = 1 := by
  have h2 : ‖(2 : ℚ_[2])‖ = 2⁻¹ := by
    have := Padic.norm_p (p := 2); exact_mod_cast this
  have hlt : ‖2 * y‖ < ‖(1 : ℚ_[2])‖ := by
    rw [norm_mul, h2, norm_one]; nlinarith [norm_nonneg y]
  rw [IsUltrametricDist.norm_add_eq_max_of_norm_ne_norm hlt.ne', norm_one]
  exact max_eq_left (by rw [norm_one] at hlt; exact hlt.le)

/-- For odd `u` and `‖t‖ ≤ 1`: `‖u + 2t‖ = 1`. -/
theorem norm_odd_add_two_mul {u : ℤ} (hu : Odd u) {t : ℚ_[2]} (ht : ‖t‖ ≤ 1) :
    ‖(u : ℚ_[2]) + 2 * t‖ = 1 := by
  obtain ⟨m, rfl⟩ := hu
  have : ((2 * m + 1 : ℤ) : ℚ_[2]) + 2 * t = 1 + 2 * ((m : ℚ_[2]) + t) := by push_cast; ring
  rw [this]
  refine norm_one_add_two_mul (le_trans (IsUltrametricDist.norm_add_le_max _ _) (max_le ?_ ht))
  exact Padic.norm_int_le_one m

/-- The finite differences of `(u + 2t)^{-1}`:
`Δ^j (u+2t)^{-1} = (−2)^j j! ∏_{i ≤ j} (u + 2t + 2i)^{-1}`. -/
theorem fwdDiff_iter_phi {u : ℤ} (hu : Odd u) (j : ℕ) {x : ℚ_[2]} (hx : ‖x‖ ≤ 1) :
    (Δ₂)^[j] (fun t => ((u : ℚ_[2]) + 2 * t)⁻¹) x =
      (-2) ^ j * (j.factorial : ℚ_[2]) *
        ∏ i ∈ range (j + 1), ((u : ℚ_[2]) + 2 * x + 2 * i)⁻¹ := by
  have hne : ∀ y : ℚ_[2], ‖y‖ ≤ 1 → ∀ i : ℕ, (u : ℚ_[2]) + 2 * y + 2 * i ≠ 0 := by
    intro y hy i h0
    have hyi : ‖y + i‖ ≤ 1 := le_trans (IsUltrametricDist.norm_add_le_max _ _)
      (max_le hy (IsUltrametricDist.norm_natCast_le_one _ _))
    have := norm_odd_add_two_mul hu hyi
    rw [show (u : ℚ_[2]) + 2 * (y + i) = (u : ℚ_[2]) + 2 * y + 2 * i by ring, h0,
      norm_zero] at this
    exact zero_ne_one this
  induction j generalizing x with
  | zero => simp
  | succ j ih =>
    have hx1 : ‖x + 1‖ ≤ 1 := le_trans (IsUltrametricDist.norm_add_le_max _ _)
      (max_le hx (by simp))
    rw [Function.iterate_succ_apply', fwdDiff, ih hx1, ih hx]
    set a : ℕ → ℚ_[2] := fun i => (u : ℚ_[2]) + 2 * x + 2 * i with ha
    have e1 : ∀ i : ℕ, (u : ℚ_[2]) + 2 * (x + 1) + 2 * i = a (i + 1) := by
      intro i; simp only [ha]; push_cast; ring
    simp_rw [e1]
    have e2 : ∀ i : ℕ, (u : ℚ_[2]) + 2 * x + 2 * i = a i := fun i => rfl
    simp_rw [e2]
    rw [prod_range_succ (fun i => (a (i + 1))⁻¹), prod_range_succ' (fun i => (a i)⁻¹),
      prod_range_succ' (fun i => (a i)⁻¹) (j + 1), prod_range_succ (fun i => (a (i + 1))⁻¹)]
    have h0 : a 0 ≠ 0 := hne x hx 0
    have hj : a (j + 1) ≠ 0 := hne x hx (j + 1)
    have hdiff : a 0 - a (j + 1) = -2 * ((j : ℚ_[2]) + 1) := by
      simp only [ha]; push_cast; ring
    generalize ∏ i ∈ range j, (a (i + 1))⁻¹ = P
    have key : (a (j + 1))⁻¹ - (a 0)⁻¹ = (a 0 - a (j + 1)) * (a 0)⁻¹ * (a (j + 1))⁻¹ := by
      field_simp
    rw [Nat.factorial_succ]
    push_cast
    linear_combination (-2) ^ j * (j.factorial : ℚ_[2]) * P * key +
      (-2) ^ j * (j.factorial : ℚ_[2]) * P * (a 0)⁻¹ * (a (j + 1))⁻¹ * hdiff

theorem prof_phi {u : ℤ} (hu : Odd u) : Prof geo (fun t => ((u : ℚ_[2]) + 2 * t)⁻¹) := by
  intro x j
  have hx : ‖(x : ℚ_[2])‖ ≤ 1 := IsUltrametricDist.norm_natCast_le_one _ _
  rw [fwdDiff_iter_phi hu j hx, norm_mul, norm_mul, norm_prod]
  have h2 : ‖(-2 : ℚ_[2]) ^ j‖ = geo j := by
    rw [norm_pow, norm_neg]
    have := Padic.norm_p (p := 2); simp only [geo]; congr 1
  have hf : ‖((j.factorial : ℕ) : ℚ_[2])‖ ≤ 1 := IsUltrametricDist.norm_natCast_le_one _ _
  have hp : ∏ i ∈ range (j + 1), ‖((u : ℚ_[2]) + 2 * x + 2 * i)⁻¹‖ = 1 := by
    refine Finset.prod_eq_one fun i _ => ?_
    have hyi : ‖(x : ℚ_[2]) + i‖ ≤ 1 := le_trans (IsUltrametricDist.norm_add_le_max _ _)
      (max_le hx (IsUltrametricDist.norm_natCast_le_one _ _))
    have := norm_odd_add_two_mul hu hyi
    rw [norm_inv, show (u : ℚ_[2]) + 2 * x + 2 * i = (u : ℚ_[2]) + 2 * (x + i) by ring, this,
      inv_one]
  rw [h2, hp, mul_one]
  calc geo j * ‖((j.factorial : ℕ) : ℚ_[2])‖ ≤ geo j * 1 :=
        mul_le_mul_of_nonneg_left hf (geo_nonneg j)
    _ = geo j := mul_one _

/-! ### Admissible functions -/

/-- The algebra generated by the constants of norm `≤ 1` and the functions `(u + 2t)^{-1}`,
`u` odd. -/
inductive Adm : (ℚ_[2] → ℚ_[2]) → Prop
  | const (a : ℚ_[2]) : ‖a‖ ≤ 1 → Adm fun _ => a
  | phi (u : ℤ) : Odd u → Adm fun t => ((u : ℚ_[2]) + 2 * t)⁻¹
  | add {f g : ℚ_[2] → ℚ_[2]} : Adm f → Adm g → Adm (f + g)
  | mul {f g : ℚ_[2] → ℚ_[2]} : Adm f → Adm g → Adm (f * g)

/-- Every admissible function has the geometric profile `‖Δ^j f(x)‖ ≤ 2^{-j}`. -/
theorem Adm.prof {f : ℚ_[2] → ℚ_[2]} (hf : Adm f) : Prof geo f := by
  induction hf with
  | const a ha => exact prof_const ha
  | phi u hu => exact prof_phi hu
  | add _ _ ihf ihg => exact ihf.add ihg
  | mul _ _ ihf ihg => exact ihf.geo_mul ihg

theorem Adm.pow {f : ℚ_[2] → ℚ_[2]} (hf : Adm f) (n : ℕ) : Adm fun t => f t ^ n := by
  induction n with
  | zero => simpa using Adm.const 1 (by simp)
  | succ n ih =>
    have : (fun t => f t ^ (n + 1)) = (fun t => f t ^ n) * f := by
      funext t; simp [pow_succ]
    rw [this]; exact ih.mul hf

theorem Adm.prod {ι : Type*} (s : Finset ι) {f : ι → ℚ_[2] → ℚ_[2]} (hf : ∀ i ∈ s, Adm (f i)) :
    Adm fun t => ∏ i ∈ s, f i t := by
  classical
  induction s using Finset.induction_on with
  | empty => simpa using Adm.const 1 (by simp)
  | insert a s ha ih =>
    have : (fun t => ∏ i ∈ insert a s, f i t) = f a * fun t => ∏ i ∈ s, f i t := by
      funext t; simp [Finset.prod_insert ha]
    rw [this]
    exact (hf a (mem_insert_self _ _)).mul (ih fun i hi => hf i (mem_insert_of_mem hi))

/-- The ball `‖t‖ < 2` avoids the poles of every `(u + 2t)^{-1}`, `u` odd. -/
theorem odd_add_two_mul_ne_zero {u : ℤ} (hu : Odd u) {t : ℚ_[2]}
    (ht : t ∈ Metric.ball (0 : ℚ_[2]) 2) : (u : ℚ_[2]) + 2 * t ≠ 0 := by
  obtain ⟨m, rfl⟩ := hu
  have h2 : ‖(2 : ℚ_[2])‖ = 2⁻¹ := by
    have := Padic.norm_p (p := 2); exact_mod_cast this
  rw [Metric.mem_ball, dist_zero_right] at ht
  have hlt : ‖2 * ((m : ℚ_[2]) + t)‖ < ‖(1 : ℚ_[2])‖ := by
    rw [norm_mul, h2, norm_one]
    have := IsUltrametricDist.norm_add_le_max (m : ℚ_[2]) t
    have hm := Padic.norm_int_le_one (p := 2) m
    have : ‖(m : ℚ_[2]) + t‖ < 2 := lt_of_le_of_lt this (max_lt (by linarith) ht)
    linarith
  have e : ((2 * m + 1 : ℤ) : ℚ_[2]) + 2 * t = 1 + 2 * ((m : ℚ_[2]) + t) := by push_cast; ring
  rw [e]
  intro h0
  have := IsUltrametricDist.norm_add_eq_max_of_norm_ne_norm hlt.ne'
  rw [h0, norm_zero, norm_one] at this
  have h1 : (1 : ℝ) ≤ max 1 ‖2 * ((m : ℚ_[2]) + t)‖ := le_max_left _ _
  linarith

/-- Admissible functions are closed under differentiation on the ball `‖t‖ < 2`. -/
theorem Adm.hasDerivAt {f : ℚ_[2] → ℚ_[2]} (hf : Adm f) :
    ∃ g, Adm g ∧ ∀ t ∈ Metric.ball (0 : ℚ_[2]) 2, HasDerivAt f (g t) t := by
  induction hf with
  | const a _ => exact ⟨fun _ => 0, Adm.const 0 (by simp), fun t _ => hasDerivAt_const t a⟩
  | phi u hu =>
    refine ⟨(fun _ => (-2 : ℚ_[2])) * ((fun t => ((u : ℚ_[2]) + 2 * t)⁻¹) *
      (fun t => ((u : ℚ_[2]) + 2 * t)⁻¹)), (Adm.const _ ?_).mul ((Adm.phi u hu).mul
        (Adm.phi u hu)), fun t ht => ?_⟩
    · rw [norm_neg]; have := Padic.norm_p (p := 2); push_cast at this; rw [this]; norm_num
    · have hd : HasDerivAt (fun t => (u : ℚ_[2]) + 2 * t) 2 t := by
        simpa using ((hasDerivAt_id t).const_mul (2 : ℚ_[2])).const_add (u : ℚ_[2])
      have := hd.inv (odd_add_two_mul_ne_zero hu ht)
      convert this using 1
      simp only [Pi.mul_apply]
      field_simp
  | add _ _ ihf ihg =>
    obtain ⟨g₁, hg₁, hd₁⟩ := ihf
    obtain ⟨g₂, hg₂, hd₂⟩ := ihg
    exact ⟨g₁ + g₂, hg₁.add hg₂, fun t ht => (hd₁ t ht).add (hd₂ t ht)⟩
  | @mul f g hf hg ihf ihg =>
    obtain ⟨g₁, hg₁, hd₁⟩ := ihf
    obtain ⟨g₂, hg₂, hd₂⟩ := ihg
    refine ⟨g₁ * g + f * g₂, (hg₁.mul hg).add (hf.mul hg₂), fun t ht => ?_⟩
    exact (hd₁ t ht).mul (hd₂ t ht)

end Hankel2
