import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C101

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 101, `[4/13, 1/3]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 101: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs101 : ArcsD where
  J := 5
  arcs := [((1/2, -3/2), some 0), ((-3/2, 5), some 1), ((0, 1/2), some 2), ((3/2, -4), some 2), ((-1/2, 5/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs101_ok : cellArcsOK Cert.CertData.c101 arcs101 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
