import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C102

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 102, `[1/3, 4/11]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 102: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs102 : ArcsD where
  J := 5
  arcs := [((-1/2, 3/2), some 0), ((3/2, -4), some 1), ((0, 1/2), some 2), ((-3/2, 5), some 2), ((1/2, -1/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs102_ok : cellArcsOK Cert.CertData.c102 arcs102 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
