import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C103

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 103, `[4/11, 3/8]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 103: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs103 : ArcsD where
  J := 5
  arcs := [((3/2, -4), some 0), ((-1/2, 3/2), some 1), ((0, 1/2), some 2), ((1/2, -1/2), some 2), ((-3/2, 5), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs103_ok : cellArcsOK Cert.CertData.c103 arcs103 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
