import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C106

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 106, `[3/7, 4/9]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 106: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs106 : ArcsD where
  J := 4
  arcs := [((-1/2, 3/2), some 0), ((3/2, -3), some 1), ((0, 1/2), some 2), ((-3/2, 4), some 2), ((1/2, -1/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs106_ok : cellArcsOK Cert.CertData.c106 arcs106 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
