import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C108

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 108, `[1/2, 4/7]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 108: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs108 : ArcsD where
  J := 4
  arcs := [((-3/2, 3), some 0), ((1/2, -1/2), some 1), ((0, 1/2), some 2), ((-1/2, 3/2), some 2), ((3/2, -2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs108_ok : cellArcsOK Cert.CertData.c108 arcs108 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
