import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C109

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 109, `[4/7, 3/5]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 109: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs109 : ArcsD where
  J := 3
  arcs := [((1/2, -1/2), some 0), ((-3/2, 3), some 1), ((0, 1/2), some 2), ((3/2, -2), some 2), ((-1/2, 3/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs109_ok : cellArcsOK Cert.CertData.c109 arcs109 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
