import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C111

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 111, `[2/3, 3/4]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 111: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs111 : ArcsD where
  J := 3
  arcs := [((3/2, -2), some 0), ((1/2, -1/2), some 1), ((0, 1/2), some 2), ((-1/2, 3/2), some 2), ((-3/2, 3), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs111_ok : cellArcsOK Cert.CertData.c111 arcs111 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
