import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C112

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 112, `[3/4, 4/5]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 112: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs112 : ArcsD where
  J := 3
  arcs := [((-3/2, 2), some 0), ((1/2, -1/2), some 1), ((0, 1/2), some 2), ((-1/2, 3/2), some 2), ((3/2, -1), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs112_ok : cellArcsOK Cert.CertData.c112 arcs112 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
