import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C115

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 115, `[4/3, 3/2]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 115: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs115 : ArcsD where
  J := 2
  arcs := [((3/2, -1), some 0), ((-1/2, 1/2), some 1), ((0, 1/2), some 2), ((1/2, 1/2), some 2), ((-3/2, 2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs115_ok : cellArcsOK Cert.CertData.c115 arcs115 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
