import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C116

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 116, `[3/2, 2]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 116: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs116 : ArcsD where
  J := 2
  arcs := [((-3/2, 1), none), ((-1/2, 1/2), some 1), ((0, 1/2), some 2), ((1/2, 1/2), some 2), ((3/2, 0), some 1), ((0, 1), none)]

set_option maxRecDepth 100000 in
theorem arcs116_ok : cellArcsOK Cert.CertData.c116 arcs116 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
