import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C118

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 118, `[3, 7/2]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 118: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs118 : ArcsD where
  J := 1
  arcs := [((-1/2, 1/2), none), ((3/2, 0), none), ((0, 1/2), none), ((-3/2, 1), none), ((1/2, 1/2), none), ((0, 1), none)]

set_option maxRecDepth 100000 in
theorem arcs118_ok : cellArcsOK Cert.CertData.c118 arcs118 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
