import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C17

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 17, `[4/69, 1/17]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 17: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs17 : ArcsD where
  J := 26
  arcs := [((1/2, -17/2), some 0), ((-3/2, 26), some 1), ((0, 1/2), some 2), ((3/2, -25), some 2), ((-1/2, 19/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs17_ok : cellArcsOK Cert.CertData.c17 arcs17 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
