import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C21

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 21, `[2/33, 3/49]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 21: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs21 : ArcsD where
  J := 25
  arcs := [((-1/2, 17/2), some 0), ((-3/2, 25), some 1), ((0, 1/2), some 2), ((3/2, -24), some 2), ((1/2, -15/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs21_ok : cellArcsOK Cert.CertData.c21 arcs21 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
