import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C23

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 23, `[4/65, 1/16]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 23: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs23 : ArcsD where
  J := 25
  arcs := [((3/2, -24), some 0), ((-1/2, 17/2), some 1), ((0, 1/2), some 2), ((1/2, -15/2), some 2), ((-3/2, 25), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs23_ok : cellArcsOK Cert.CertData.c23 arcs23 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
