import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C24

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 24, `[1/16, 4/63]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 24: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs24 : ArcsD where
  J := 25
  arcs := [((-3/2, 24), some 0), ((1/2, -15/2), some 1), ((0, 1/2), some 2), ((-1/2, 17/2), some 2), ((3/2, -23), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs24_ok : cellArcsOK Cert.CertData.c24 arcs24 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
