import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C27

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 27, `[2/31, 3/46]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 27: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs27 : ArcsD where
  J := 24
  arcs := [((3/2, -23), some 0), ((1/2, -15/2), some 1), ((0, 1/2), some 2), ((-1/2, 17/2), some 2), ((-3/2, 24), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs27_ok : cellArcsOK Cert.CertData.c27 arcs27 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
