import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C3

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 3, `[2/39, 3/58]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 3: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs3 : ArcsD where
  J := 30
  arcs := [((3/2, -29), some 0), ((1/2, -19/2), some 1), ((0, 1/2), some 2), ((-1/2, 21/2), some 2), ((-3/2, 30), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs3_ok : cellArcsOK Cert.CertData.c3 arcs3 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
