import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C31

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 31, `[4/59, 3/44]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 31: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs31 : ArcsD where
  J := 23
  arcs := [((3/2, -22), some 0), ((-1/2, 15/2), some 1), ((0, 1/2), some 2), ((1/2, -13/2), some 2), ((-3/2, 23), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs31_ok : cellArcsOK Cert.CertData.c31 arcs31 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
