import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C37

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 37, `[4/55, 3/41]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 37: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs37 : ArcsD where
  J := 21
  arcs := [((1/2, -13/2), some 0), ((-3/2, 21), some 1), ((0, 1/2), some 2), ((3/2, -20), some 2), ((-1/2, 15/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs37_ok : cellArcsOK Cert.CertData.c37 arcs37 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
