import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C38

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 38, `[3/41, 2/27]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 38: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs38 : ArcsD where
  J := 21
  arcs := [((1/2, -13/2), some 0), ((3/2, -20), some 1), ((0, 1/2), some 2), ((-3/2, 21), some 2), ((-1/2, 15/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs38_ok : cellArcsOK Cert.CertData.c38 arcs38 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
