import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C4

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 4, `[3/58, 4/77]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 4: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs4 : ArcsD where
  J := 30
  arcs := [((-3/2, 29), some 0), ((1/2, -19/2), some 1), ((0, 1/2), some 2), ((-1/2, 21/2), some 2), ((3/2, -28), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs4_ok : cellArcsOK Cert.CertData.c4 arcs4 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
