import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C40

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 40, `[3/40, 4/53]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 40: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs40 : ArcsD where
  J := 21
  arcs := [((-3/2, 20), some 0), ((1/2, -13/2), some 1), ((0, 1/2), some 2), ((-1/2, 15/2), some 2), ((3/2, -19), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs40_ok : cellArcsOK Cert.CertData.c40 arcs40 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
