import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C42

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 42, `[1/13, 4/51]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 42: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs42 : ArcsD where
  J := 20
  arcs := [((-1/2, 13/2), some 0), ((3/2, -19), some 1), ((0, 1/2), some 2), ((-3/2, 20), some 2), ((1/2, -11/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs42_ok : cellArcsOK Cert.CertData.c42 arcs42 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
