import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C45

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 45, `[2/25, 3/37]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 45: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs45 : ArcsD where
  J := 19
  arcs := [((-1/2, 13/2), some 0), ((-3/2, 19), some 1), ((0, 1/2), some 2), ((3/2, -18), some 2), ((1/2, -11/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs45_ok : cellArcsOK Cert.CertData.c45 arcs45 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
