import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C46

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 46, `[3/37, 4/49]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 46: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs46 : ArcsD where
  J := 19
  arcs := [((-1/2, 13/2), some 0), ((3/2, -18), some 1), ((0, 1/2), some 2), ((-3/2, 19), some 2), ((1/2, -11/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs46_ok : cellArcsOK Cert.CertData.c46 arcs46 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
