import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C49

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 49, `[4/47, 3/35]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 49: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs49 : ArcsD where
  J := 18
  arcs := [((1/2, -11/2), some 0), ((-3/2, 18), some 1), ((0, 1/2), some 2), ((3/2, -17), some 2), ((-1/2, 13/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs49_ok : cellArcsOK Cert.CertData.c49 arcs49 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
