import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C5

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 5, `[4/77, 1/19]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 5: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs5 : ArcsD where
  J := 29
  arcs := [((1/2, -19/2), some 0), ((-3/2, 29), some 1), ((0, 1/2), some 2), ((3/2, -28), some 2), ((-1/2, 21/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs5_ok : cellArcsOK Cert.CertData.c5 arcs5 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
