import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C52

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 52, `[3/34, 4/45]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 52: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs52 : ArcsD where
  J := 18
  arcs := [((-3/2, 17), some 0), ((1/2, -11/2), some 1), ((0, 1/2), some 2), ((-1/2, 13/2), some 2), ((3/2, -16), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs52_ok : cellArcsOK Cert.CertData.c52 arcs52 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
