import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C53

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 53, `[4/45, 1/11]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 53: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs53 : ArcsD where
  J := 17
  arcs := [((1/2, -11/2), some 0), ((-3/2, 17), some 1), ((0, 1/2), some 2), ((3/2, -16), some 2), ((-1/2, 13/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs53_ok : cellArcsOK Cert.CertData.c53 arcs53 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
