import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C55

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 55, `[4/43, 3/32]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 55: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs55 : ArcsD where
  J := 17
  arcs := [((3/2, -16), some 0), ((-1/2, 11/2), some 1), ((0, 1/2), some 2), ((1/2, -9/2), some 2), ((-3/2, 17), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs55_ok : cellArcsOK Cert.CertData.c55 arcs55 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
