import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C56

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 56, `[3/32, 2/21]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 56: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs56 : ArcsD where
  J := 17
  arcs := [((-3/2, 16), some 0), ((-1/2, 11/2), some 1), ((0, 1/2), some 2), ((1/2, -9/2), some 2), ((3/2, -15), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs56_ok : cellArcsOK Cert.CertData.c56 arcs56 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
