import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C58

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 58, `[3/31, 4/41]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 58: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs58 : ArcsD where
  J := 16
  arcs := [((-1/2, 11/2), some 0), ((3/2, -15), some 1), ((0, 1/2), some 2), ((-3/2, 16), some 2), ((1/2, -9/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs58_ok : cellArcsOK Cert.CertData.c58 arcs58 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
