import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C60

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 60, `[1/10, 4/39]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 60: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs60 : ArcsD where
  J := 16
  arcs := [((-3/2, 15), some 0), ((1/2, -9/2), some 1), ((0, 1/2), some 2), ((-1/2, 11/2), some 2), ((3/2, -14), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs60_ok : cellArcsOK Cert.CertData.c60 arcs60 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
