import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C64

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 64, `[3/28, 4/37]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 64: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs64 : ArcsD where
  J := 15
  arcs := [((-3/2, 14), some 0), ((1/2, -9/2), some 1), ((0, 1/2), some 2), ((-1/2, 11/2), some 2), ((3/2, -13), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs64_ok : cellArcsOK Cert.CertData.c64 arcs64 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
