import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C65

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 65, `[4/37, 1/9]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 65: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs65 : ArcsD where
  J := 14
  arcs := [((1/2, -9/2), some 0), ((-3/2, 14), some 1), ((0, 1/2), some 2), ((3/2, -13), some 2), ((-1/2, 11/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs65_ok : cellArcsOK Cert.CertData.c65 arcs65 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
