import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C66

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 66, `[1/9, 4/35]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 66: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs66 : ArcsD where
  J := 14
  arcs := [((-1/2, 9/2), some 0), ((3/2, -13), some 1), ((0, 1/2), some 2), ((-3/2, 14), some 2), ((1/2, -7/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs66_ok : cellArcsOK Cert.CertData.c66 arcs66 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
