import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C67

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 67, `[4/35, 3/26]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 67: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs67 : ArcsD where
  J := 14
  arcs := [((3/2, -13), some 0), ((-1/2, 9/2), some 1), ((0, 1/2), some 2), ((1/2, -7/2), some 2), ((-3/2, 14), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs67_ok : cellArcsOK Cert.CertData.c67 arcs67 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
