import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C69

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 69, `[2/17, 3/25]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 69: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs69 : ArcsD where
  J := 13
  arcs := [((-1/2, 9/2), some 0), ((-3/2, 13), some 1), ((0, 1/2), some 2), ((3/2, -12), some 2), ((1/2, -7/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs69_ok : cellArcsOK Cert.CertData.c69 arcs69 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
