import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C7

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 7, `[4/75, 3/56]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 7: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs7 : ArcsD where
  J := 29
  arcs := [((3/2, -28), some 0), ((-1/2, 19/2), some 1), ((0, 1/2), some 2), ((1/2, -17/2), some 2), ((-3/2, 29), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs7_ok : cellArcsOK Cert.CertData.c7 arcs7 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
