import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C71

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 71, `[4/33, 1/8]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 71: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs71 : ArcsD where
  J := 13
  arcs := [((3/2, -12), some 0), ((-1/2, 9/2), some 1), ((0, 1/2), some 2), ((1/2, -7/2), some 2), ((-3/2, 13), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs71_ok : cellArcsOK Cert.CertData.c71 arcs71 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
