import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C73

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 73, `[4/31, 3/23]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 73: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs73 : ArcsD where
  J := 12
  arcs := [((1/2, -7/2), some 0), ((-3/2, 12), some 1), ((0, 1/2), some 2), ((3/2, -11), some 2), ((-1/2, 9/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs73_ok : cellArcsOK Cert.CertData.c73 arcs73 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
