import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C79

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 79, `[4/27, 3/20]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 79: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs79 : ArcsD where
  J := 11
  arcs := [((3/2, -10), some 0), ((-1/2, 7/2), some 1), ((0, 1/2), some 2), ((1/2, -5/2), some 2), ((-3/2, 11), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs79_ok : cellArcsOK Cert.CertData.c79 arcs79 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
