import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C8

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 8, `[3/56, 2/37]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 8: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs8 : ArcsD where
  J := 29
  arcs := [((-3/2, 28), some 0), ((-1/2, 19/2), some 1), ((0, 1/2), some 2), ((1/2, -17/2), some 2), ((3/2, -27), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs8_ok : cellArcsOK Cert.CertData.c8 arcs8 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
