import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C80

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 80, `[3/20, 2/13]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 80: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs80 : ArcsD where
  J := 11
  arcs := [((-3/2, 10), some 0), ((-1/2, 7/2), some 1), ((0, 1/2), some 2), ((1/2, -5/2), some 2), ((3/2, -9), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs80_ok : cellArcsOK Cert.CertData.c80 arcs80 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
