import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C81

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 81, `[2/13, 3/19]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 81: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs81 : ArcsD where
  J := 10
  arcs := [((-1/2, 7/2), some 0), ((-3/2, 10), some 1), ((0, 1/2), some 2), ((3/2, -9), some 2), ((1/2, -5/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs81_ok : cellArcsOK Cert.CertData.c81 arcs81 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
