import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C88

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 88, `[3/16, 4/21]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 88: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs88 : ArcsD where
  J := 9
  arcs := [((-3/2, 8), some 0), ((1/2, -5/2), some 1), ((0, 1/2), some 2), ((-1/2, 7/2), some 2), ((3/2, -7), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs88_ok : cellArcsOK Cert.CertData.c88 arcs88 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
