import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C89

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 89, `[4/21, 1/5]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 89: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs89 : ArcsD where
  J := 8
  arcs := [((1/2, -5/2), some 0), ((-3/2, 8), some 1), ((0, 1/2), some 2), ((3/2, -7), some 2), ((-1/2, 7/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs89_ok : cellArcsOK Cert.CertData.c89 arcs89 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
