import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C9

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 9, `[2/37, 3/55]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 9: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs9 : ArcsD where
  J := 28
  arcs := [((-1/2, 19/2), some 0), ((-3/2, 28), some 1), ((0, 1/2), some 2), ((3/2, -27), some 2), ((1/2, -17/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs9_ok : cellArcsOK Cert.CertData.c9 arcs9 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
