import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C90

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 90, `[1/5, 4/19]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 90: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs90 : ArcsD where
  J := 8
  arcs := [((-1/2, 5/2), some 0), ((3/2, -7), some 1), ((0, 1/2), some 2), ((-3/2, 8), some 2), ((1/2, -3/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs90_ok : cellArcsOK Cert.CertData.c90 arcs90 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
