import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C91

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 91, `[4/19, 3/14]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 91: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs91 : ArcsD where
  J := 8
  arcs := [((3/2, -7), some 0), ((-1/2, 5/2), some 1), ((0, 1/2), some 2), ((1/2, -3/2), some 2), ((-3/2, 8), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs91_ok : cellArcsOK Cert.CertData.c91 arcs91 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
