import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C92

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 92, `[3/14, 2/9]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 92: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs92 : ArcsD where
  J := 8
  arcs := [((-3/2, 7), some 0), ((-1/2, 5/2), some 1), ((0, 1/2), some 2), ((1/2, -3/2), some 2), ((3/2, -6), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs92_ok : cellArcsOK Cert.CertData.c92 arcs92 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
