import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C93

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 93, `[2/9, 3/13]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 93: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs93 : ArcsD where
  J := 7
  arcs := [((-1/2, 5/2), some 0), ((-3/2, 7), some 1), ((0, 1/2), some 2), ((3/2, -6), some 2), ((1/2, -3/2), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs93_ok : cellArcsOK Cert.CertData.c93 arcs93 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
