import RequestProject.TwoAdic.AsmArcs
import RequestProject.TwoAdic.CertData.C96

/-! Generated by `scripts/gen_arcs_two_adic.py`: the arcs of cell 96, `[1/4, 4/15]`, and their
check against the class types of the certificate (`decide +kernel`). -/

namespace TwoAdicWin.Arc.ArcData

/-- The arcs of cell 96: right ends `(c0, c1)` (`c0 + c1 u`) and type indices. -/
def arcs96 : ArcsD where
  J := 7
  arcs := [((-3/2, 6), some 0), ((1/2, -3/2), some 1), ((0, 1/2), some 2), ((-1/2, 5/2), some 2), ((3/2, -5), some 1), ((0, 1), some 0)]

set_option maxRecDepth 100000 in
theorem arcs96_ok : cellArcsOK Cert.CertData.c96 arcs96 = true := by decide +kernel

end TwoAdicWin.Arc.ArcData
