import RequestProject.TwoAdic.CertCheck

/-!
# The arcs of the circle model: a checker for the class types of the certificate (II, Cor. 5.4)

For a prime `ℓ = u n` and a residue `r` mod `ℓ`, put `x = r/n`.  The class of `r` has the nodes
`k = r + jℓ` with `|k| ≤ 3n/2`, i.e. `x + j u ∈ [−3/2, 3/2]`; a node is hs iff `ℓ ≤ 2|k| − 1`, i.e.
`|x + j u| ≥ u/2 + 1/(2n)`; and the zeros `z` with `ℓ ∣ 2(−k − z)` correspond to the `j` with
`1 − n ≤ 2r + (2j − 1)ℓ ≤ n − 1`, i.e. `2x + (2j−1)u ∈ [−1 + 1/n, 1 − 1/n]`.

An **arc** is a pair of affine functions `lo(u) ≤ hi(u)` (`Aff`, `c0 + c1 u`).  The checker decides,
for every shift `j ∈ [−J, J]`, by affine inequalities at the two ends `u = a, b` of the cell, that the
shifted arc lies inside or outside the node range, the hs region and the zero range (`nodeSt`,
`zeroSt`).  If it succeeds, every residue `r` with `n·lo(u) + 1 ≤ r ≤ n·hi(u) − 1` has the class data
`(N, #hs, z) = arcInfo` (proved in `AsmArcsSound.lean`), hence the kept runs `runsOf`.

`cellArcsOK c D` checks a chain of arcs `0 = e₀ ≤ e₁ ≤ ⋯ ≤ e_m = u` on the cell `c`, that the runs
of every arc are the runs of the certificate type it is assigned to (or empty), that `J a > 3/2`, and
that for every type the total length of its arcs is at most `meas_t(u)` at both ends of the cell, where
`meas_t ≥ 0`.  The data are generated by `scripts/gen_arcs_two_adic.py`.
-/

namespace TwoAdicWin.Arc

open Cert

/-- An affine function `c0 + c1 u`. -/
abbrev Aff := ℚ × ℚ

/-- `c0 + c1 u`. -/
def affV (f : Aff) (u : ℚ) : ℚ := f.1 + f.2 * u

/-- `f ≥ c` at both ends. -/
def geAB (a b : ℚ) (f : Aff) (c : ℚ) : Bool := decide (c ≤ affV f a) && decide (c ≤ affV f b)

/-- `f ≤ c` at both ends. -/
def leAB (a b : ℚ) (f : Aff) (c : ℚ) : Bool := decide (affV f a ≤ c) && decide (affV f b ≤ c)

/-- The status of the shift `j` of the arc `[lo, hi]` with respect to the node range and the hs
region: `some (node?, hs?)`, or `none` if undecided. -/
def nodeSt (a b : ℚ) (lo hi : Aff) (j : ℤ) : Option (Bool × Bool) :=
  if geAB a b (lo.1, lo.2 + j) (-3 / 2) && leAB a b (hi.1, hi.2 + j) (3 / 2) then
    if geAB a b (lo.1, lo.2 + j - 1 / 2) 0 || leAB a b (hi.1, hi.2 + j + 1 / 2) 0 then
      some (true, true)
    else if geAB a b (lo.1, lo.2 + j + 1 / 2) 0 && leAB a b (hi.1, hi.2 + j - 1 / 2) 0 then
      some (true, false)
    else none
  else if leAB a b (hi.1, hi.2 + j) (-3 / 2) || geAB a b (lo.1, lo.2 + j) (3 / 2) then
    some (false, false)
  else none

/-- The status of the shift `j` with respect to the zero range: `some zero?`, or `none`. -/
def zeroSt (a b : ℚ) (lo hi : Aff) (j : ℤ) : Option Bool :=
  if geAB a b (2 * lo.1, 2 * lo.2 + 2 * j - 1) (-1) && leAB a b (2 * hi.1, 2 * hi.2 + 2 * j - 1) 1 then
    some true
  else if leAB a b (2 * hi.1, 2 * hi.2 + 2 * j - 1) (-1) || geAB a b (2 * lo.1, 2 * lo.2 + 2 * j - 1) 1 then
    some false
  else none

/-- The shifts `j ∈ [−J, J]`. -/
def shifts (J : ℕ) : List ℤ := (List.range (2 * J + 1)).map fun i : ℕ => (i : ℤ) - J

def isNodeB (a b : ℚ) (lo hi : Aff) (j : ℤ) : Bool :=
  match nodeSt a b lo hi j with
  | some (true, _) => true
  | _ => false

def isHsB (a b : ℚ) (lo hi : Aff) (j : ℤ) : Bool := nodeSt a b lo hi j == some (true, true)

def isZeroB (a b : ℚ) (lo hi : Aff) (j : ℤ) : Bool := zeroSt a b lo hi j == some true

/-- Every shift is decided. -/
def allDet (a b : ℚ) (lo hi : Aff) (J : ℕ) : Bool :=
  (shifts J).all fun j => (nodeSt a b lo hi j).isSome && (zeroSt a b lo hi j).isSome

/-- The class data `(N, #hs, z)` of the arc. -/
def arcN (a b : ℚ) (lo hi : Aff) (J : ℕ) : ℕ := ((shifts J).filter (isNodeB a b lo hi)).length
def arcH (a b : ℚ) (lo hi : Aff) (J : ℕ) : ℕ := ((shifts J).filter (isHsB a b lo hi)).length
def arcZ (a b : ℚ) (lo hi : Aff) (J : ℕ) : ℕ := ((shifts J).filter (isZeroB a b lo hi)).length

/-- The kept runs of a class with `N` nodes, `nh` of them hs, and `z` zeros (II, Lemma 5.3):
hs nodes are kept; the non-hs nodes are kept iff `μ = 1` and `N − z ≥ 1`. -/
def runsOf (N nh z : ℕ) : List RunD :=
  let v : ℤ := (N : ℤ) - z
  let mk : ℕ := if (2 ≤ N ∨ 1 ≤ z) ∧ 1 ≤ v then N - nh else 0
  if nh = 0 ∧ mk = 0 then [] else [((v : ℚ), true, nh), ((v : ℚ), false, mk)]

/-- The default type. -/
def typ0 : TypeD := ⟨0, 0, []⟩

/-- The arc data of a cell: the shift range `J` and the arcs (right end, type index). -/
structure ArcsD where
  J : ℕ
  arcs : List (Aff × Option ℕ)

/-- The check of one arc. -/
def arcOK (c : CellD) (J : ℕ) (lo hi : Aff) (idx : Option ℕ) : Bool :=
  allDet c.a c.b lo hi J &&
    match idx with
    | none => runsOf (arcN c.a c.b lo hi J) (arcH c.a c.b lo hi J) (arcZ c.a c.b lo hi J) == []
    | some t => decide (t < c.types.length) &&
        ((c.types.getD t typ0).runs ==
          runsOf (arcN c.a c.b lo hi J) (arcH c.a c.b lo hi J) (arcZ c.a c.b lo hi J))

/-- The chain of arcs is monotone at both ends and ends at `u`. -/
def chainOK (a b : ℚ) : Aff → List (Aff × Option ℕ) → Bool
  | lo, [] => decide (lo = (0, 1))
  | lo, (hi, _) :: rest =>
      decide (affV lo a ≤ affV hi a) && decide (affV lo b ≤ affV hi b) && chainOK a b hi rest

/-- Every arc is checked. -/
def arcsAllOK (c : CellD) (J : ℕ) : Aff → List (Aff × Option ℕ) → Bool
  | _, [] => true
  | lo, (hi, idx) :: rest => arcOK c J lo hi idx && arcsAllOK c J hi rest

/-- The total length (affine) of the arcs of type `t`. -/
def measSum (t : ℕ) : Aff → List (Aff × Option ℕ) → Aff
  | _, [] => (0, 0)
  | lo, (hi, idx) :: rest =>
      let m := measSum t hi rest
      if idx = some t then (m.1 + (hi.1 - lo.1), m.2 + (hi.2 - lo.2)) else m

/-- The measures: the arcs of each type have total length `≤ meas_t`, and `meas_t ≥ 0`, at both
ends. -/
def measOK (c : CellD) (D : ArcsD) : Bool :=
  (List.range c.types.length).all fun t =>
    let m := measSum t (0, 0) D.arcs
    let ty := c.types.getD t typ0
    decide (affV m c.a ≤ measQ ty c.a) && decide (affV m c.b ≤ measQ ty c.b) &&
      decide (0 ≤ measQ ty c.a) && decide (0 ≤ measQ ty c.b)

/-- **The check of the arcs of a cell.** -/
def cellArcsOK (c : CellD) (D : ArcsD) : Bool :=
  decide (0 < c.a) && decide (c.a ≤ c.b) && decide (3 / 2 < (D.J : ℚ) * c.a) &&
    chainOK c.a c.b (0, 0) D.arcs && arcsAllOK c D.J (0, 0) D.arcs && measOK c D

end TwoAdicWin.Arc
