"""Generate the Lean data modules of the certificate of II, Prop. 7.1.

Input: certificates/cert_uniform_M96_delta0.4286.json.
Output: RequestProject/TwoAdic/CertData/C<k>.lean (one module per cell, 119 cells) and
RequestProject/TwoAdic/CertAll.lean (the concatenation and the combined block).

For every type, the kept weights `alpha` (at delta = 3/7) are grouped into runs (N - z, hs, count) with
N - z = alpha - (10/7) hs (an integer).  For every subcell and type, a dual multiplier mu is chosen
minimising the weak-duality bound D(mu) = sum_k (alpha_k - tau - mu)^+ + mu^2/4 over the candidates
{2j} and {alpha_k - tau}; it reproduces psi() of check_uniform.py exactly (checked by cert_dual.py).
"""
import json, sys, os
from fractions import Fraction as F
sys.set_int_max_str_digits(0)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CERT = os.path.join(ROOT, 'certificates', 'cert_uniform_M96_delta0.4286.json')
OUTD = os.path.join(ROOT, 'RequestProject', 'TwoAdic', 'CertData')
DEN = 10 ** 15


def runs_of(alphas):
    runs = []
    for a, hs in alphas:
        if runs and runs[-1][0] == a and runs[-1][1] == hs:
            runs[-1][2] += 1
        else:
            runs.append([a, hs, 1])
    return runs


def D(runs, lt, mu):
    return sum(cnt * max(F(0), a - lt - mu) for a, hs, cnt in runs) + mu * mu / 4


def best_mu(runs, lt):
    cands = [F(2 * j) for j in range(0, 64)] + [a - lt for a, _, _ in runs]
    cands = [c for c in cands if c >= 0]
    return min(cands, key=lambda m: (D(runs, lt, m), m))


def q(x):
    x = F(x)
    if x.denominator == 1:
        return str(x.numerator)
    return f"{x.numerator}/{x.denominator}"


def ceil_div(x):
    """smallest k/DEN >= x"""
    k = -((-x.numerator * DEN) // x.denominator)
    return F(k, DEN)


def main():
    d = json.load(open(CERT))
    delta = F(3, 7)
    cells = d['cells']
    os.makedirs(OUTD, exist_ok=True)
    prev_b = F(1, 20)
    total = F(0)
    exact_total = F(0)
    blocks = []
    for k, c in enumerate(cells):
        ca, cb = F(c['a']), F(c['b'])
        assert ca == prev_b
        types = []
        for t in c['types']:
            al = [(F(x), int(h)) for x, h in t['alphas']]
            runs = runs_of(al)
            rr = []
            for a, hs, cnt in runs:
                base = a - (1 + delta) * hs
                assert base.denominator == 1
                rr.append((base, hs, cnt))
            types.append((F(t['m0']), F(t['m1']), runs, rr))
        subs = []
        a = ca
        step = F(0)
        for sc in c['subcells']:
            sa, sb, lt, h = F(sc['a']), F(sc['b']), F(sc['lt']), F(sc['h'])
            assert sa == a
            mus = [best_mu(runs, lt) for (_, _, runs, _) in types]
            subs.append((sb, lt, h, mus))
            step += h * (sb - sa)
            a = sb
        assert a == cb
        S = ceil_div(step)
        exact_total += step
        total += S
        prev_b = cb
        tstr = ',\n    '.join(
            '⟨' + q(m0) + ', ' + q(m1) + ', [' +
            ', '.join(f"({q(b)}, {'true' if hs else 'false'}, {cnt})" for b, hs, cnt in rr) + ']⟩'
            for (m0, m1, _, rr) in types)
        sstr = ',\n    '.join(
            f"({q(sb)}, {q(lt)}, {q(h)}, [{', '.join(q(m) for m in mus)}])"
            for (sb, lt, h, mus) in subs)
        name = f"c{k}"
        src = f"""import RequestProject.TwoAdic.CertCheck

/-! Generated by `scripts/gen_cert_two_adic.py` from
`certificates/cert_uniform_M96_delta0.4286.json`: cell {k}, `[{q(ca)}, {q(cb)}]`, with its class types
(runs `(N − z, hs, multiplicity)`, measure `m0 + m1·u`) and its {len(subs)} subcells
`(b, τ, h, [μ_t])`, checked by kernel evaluation (`decide +kernel`). -/

namespace TwoAdicWin.Cert.CertData

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Cell {k}. -/
def {name} : CellD where
  a := {q(ca)}
  b := {q(cb)}
  types := [
    {tstr}]
  subs := [
    {sstr}]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem {name}_ok : cellsOK ({q(ca)}) [{name}] = true := by decide +kernel

set_option maxRecDepth 100000 in
theorem {name}_last : lastCell ({q(ca)}) [{name}] = {q(cb)} := by decide +kernel

set_option maxRecDepth 100000 in
theorem {name}_sum : stepCells ({q(ca)}) [{name}] ≤ {q(S)} := by decide +kernel

theorem {name}_blk : Blk ({q(ca)}) [{name}] ({q(cb)}) ({q(S)}) :=
  ⟨{name}_ok, {name}_last, {name}_sum⟩

end TwoAdicWin.Cert.CertData
"""
        open(os.path.join(OUTD, f"C{k}.lean"), 'w').write(src)
        blocks.append((name, ca, cb, S))
    assert prev_b == F(7, 2)
    assert exact_total == F(d['step'])
    # combined module
    imports = '\n'.join(f"import RequestProject.TwoAdic.CertData.C{k}" for k in range(len(cells)))
    lst = ' ++ '.join(f"[{n}]" for n, _, _, _ in blocks)
    term = f"CertData.{blocks[0][0]}_blk"
    for n, _, _, _ in blocks[1:]:
        term = f"blk_app ({term}) CertData.{n}_blk"
    src = f"""{imports}

/-!
# The certificate of II, Prop. 7.1 (generated by `scripts/gen_cert_two_adic.py`)

`certCells` is the full list of the 119 kernel-checked cells covering `[1/20, 7/2]`;
**`certCells_blk`**: the chain is checked, ends at `7/2`, and its step sum `∑ h (b − a)` is at most
`stepBound = {q(total)}` (≈ {float(total):.13f}; the exact step sum of the file is
≈ {float(exact_total):.13f}).
-/

namespace TwoAdicWin.Cert

open CertData

/-- The full certificate. -/
def certCells : List CellD := {lst}

/-- The bound on the step sum `∑ h_i (b_i − a_i)`. -/
def stepBound : ℚ := {q(total)}

set_option maxRecDepth 100000 in
/-- **The certificate is checked.** -/
theorem certCells_blk : Blk (1/20) certCells (7/2) stepBound := by
  have h := {term}
  refine ⟨h.1, h.2.1, h.2.2.trans (le_of_eq ?_)⟩
  unfold stepBound
  norm_num

end TwoAdicWin.Cert
"""
    open(os.path.join(ROOT, 'RequestProject', 'TwoAdic', 'CertAll.lean'), 'w').write(src)
    print('cells', len(cells), 'stepBound', float(total), 'exact', float(exact_total))


main()
